Revert "Fixed warnings on the generated Paths module."
This reverts commit 39068e7c7c741404cb19e7a85e680914e75b77b6.

It broke the build on Windows, e.g.:

utils\hsc2hs\dist\build\autogen\Paths_hsc2hs.hs:45:34:
    Not in scope: `fromIntegral'